name: flutter_scrolling_fab_animated
description: Package to add a floating button whose change of size when scroll down
version: 0.1.6
homepage: https://github.com/joaojsrbr/flutter-scrolling-fab-animated

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
